defmodule BeerocracyWeb.RulesLive do
  @moduledoc """
  How the sheet actually behaves.

  Enough rules have accumulated — maybes counting towards a day, places that
  cannot host the day that won, a rain verdict built from two numbers — that
  the behaviour is no longer self-evident from the ballot. This page states it
  once, in the same voice as the rest of the constitution.

  The rain table is generated by asking `Forecast.verdict_for/2`, so it cannot
  drift away from what the application actually does.
  """

  use BeerocracyWeb, :live_view

  alias Beerocracy.Places
  alias Beerocracy.Weather
  alias Beerocracy.Weather.Forecast
  alias Beerocracy.Week

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
     assign(socket,
       page_title: "The rules",
       window: Weather.window(),
       chances: Forecast.chance_bands(),
       millimetres: Forecast.rain_bands()
     )}
  end

  @impl true
  def render(assigns) do
    ~H"""
    <Layouts.app flash={@flash} current_scope={@current_scope}>
      <div class="px-0 py-0 sm:px-6 sm:py-10">
        <div class="sheet animate-sheet">
          <div class="sheet-perforation"></div>
          <div class="h-2 bg-ink"></div>

          <header class="px-5 pt-6 pb-5 sm:px-10 sm:pt-8">
            <p class="article-no">The Beerocracy Constitution</p>
            <h1 class="wordmark mt-1">The rules</h1>
            <p class="note mt-3">
              Everything the sheet decides on your behalf, and why. Nothing here is a
              setting — it is just what the buttons mean.
            </p>
            <p class="mt-5">
              <.link navigate={~p"/"} class="btn">Back to the ballot</.link>
            </p>
          </header>

          <section class="sheet-section">
            <.article_header no="I" title="The week">
              A sheet covers one ISO week and is wiped clean every Monday at 00:00.
              Nothing is deleted — each vote is filed under its week — so last week is
              still there, it just no longer counts.
            </.article_header>
          </section>

          <section class="sheet-section">
            <.article_header no="II" title="Days">
              The ballot runs Monday to Saturday. Tapping a day cycles it: yes, maybe,
              then nothing.
            </.article_header>

            <ul class="note mt-4 space-y-2">
              <li>
                <span class="font-bold text-ink">A maybe counts.</span>
                It is a body in the pub, so it adds to the day's total exactly like a yes.
              </li>
              <li>
                <span class="font-bold text-ink">It is counted separately too.</span>
                A day held up entirely by maybes is visibly shakier than one everybody
                committed to — solid bar for yes, hatched for maybe.
              </li>
              <li>
                <span class="font-bold text-ink">Ties go to certainty, then to the weekend.</span>
                Two days level on total: the one with fewer maybes wins. Still level: the day
                nearer the weekend, so Friday beats Monday and Saturday beats both. That
                always separates them, so the day is never left undecided.
              </li>
            </ul>
          </section>

          <section class="sheet-section">
            <.article_header no="III" title="Places">
              Everyone gets the same places in a different order.
            </.article_header>

            <ul class="note mt-4 space-y-2">
              <li>
                <span class="font-bold text-ink">The deck is shuffled per person.</span>
                Otherwise whatever sits at the top of the file gets judged while everyone
                is still interested and the bottom gets rushed. Your order is the same
                every time you open the sheet and changes each week.
              </li>
              <li>
                <span class="font-bold text-ink">A place that is shut cannot win.</span>
                The day and the place are picked together, so a Thursday-only brewery
                window is never proposed for a Tuesday. When the most-approved place
                cannot host the winning day, the sheet says so instead of quietly
                promoting the runner-up.
              </li>
              <li>
                <span class="font-bold text-ink">Seasonal places retire themselves.</span>
                A summer pop-up leaves the ballot the day after it closes.
              </li>
              <li>
                <span class="font-bold text-ink">Only the people who will be there choose.</span>
                Your swipes count when you are marked for the day that is winning — a maybe is
                enough. Not marked at all, or only free on other days, and they wait instead.
                They are kept and shown, never binned, and they join in the moment the day
                you are down for takes the lead.
              </li>
            </ul>
          </section>

          <section class="sheet-section">
            <.article_header no="IV" title="The outlook">
              The forecast covers {Forecast.window(@window)} — the hours you would
              actually be out — rather than the whole day, whose high is usually set
              mid-afternoon and answers the wrong question.
            </.article_header>

            <p class="note mt-4">
              The wording combines <span class="font-bold text-ink">how much rain</span>
              is expected with <span class="font-bold text-ink">how likely</span>
              it is. Neither number is much use alone: an evening can read 98% and expect
              0.0mm, which is a high chance of nothing in particular.
            </p>

            <div class="mt-5 overflow-x-auto">
              <table class="rules-table">
                <caption class="sr-only">
                  The rain verdict for each combination of expected rainfall and chance
                </caption>
                <thead>
                  <tr>
                    <th scope="col" class="text-left">Chance</th>
                    <th :for={{_mm, label} <- @millimetres} scope="col">{label}</th>
                  </tr>
                </thead>
                <tbody>
                  <tr :for={{chance, chance_label} <- @chances}>
                    <th scope="row" class="text-left">{chance_label}</th>
                    <td :for={{millimetres, _label} <- @millimetres}>
                      <span data-level={Forecast.verdict_for(chance, millimetres).level}>
                        {Forecast.verdict_for(chance, millimetres).phrase}
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            <p class="note mt-4">
              Anything from <span class="font-bold text-ink">Rain</span>
              rightwards counts as wet, and an outdoor place proposed for a wet day gets
              a warning on the tally. It is a warning and not a veto — people are allowed
              to sit in the rain, they should just not be surprised by it.
            </p>
          </section>

          <section class="sheet-section">
            <.article_header no="V" title="The catalogue">
              The list of places is a file, not a database table, so adding your local is
              a pull request anyone can review.
            </.article_header>

            <p class="mt-4 flex flex-wrap gap-x-5 gap-y-2">
              <a
                :if={Places.edit_url()}
                href={Places.edit_url()}
                target="_blank"
                rel="noopener noreferrer"
                class="data font-bold underline underline-offset-2"
              >
                Add a place on GitHub ↗
              </a>
              <.link navigate={~p"/places"} class="data font-bold underline underline-offset-2">
                Read the whole list →
              </.link>
            </p>
          </section>

          <footer class="border-t-2 border-ink bg-paper-edge/40 px-5 py-6 sm:px-10">
            <p class="note text-[0.8125rem]">
              Week {Week.current().week}. The table above is generated from the same code
              the ballot uses, so it cannot fall out of step with it.
            </p>
          </footer>
        </div>
      </div>
    </Layouts.app>
    """
  end

  attr :no, :string, required: true
  attr :title, :string, required: true
  slot :inner_block, required: true

  defp article_header(assigns) do
    ~H"""
    <div>
      <p class="article-no">Article {@no}</p>
      <h2 class="section-heading mt-1">{@title}</h2>
      <p class="note mt-2">{render_slot(@inner_block)}</p>
    </div>
    """
  end
end
