defmodule BeerocracyWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :beerocracy

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_beerocracy_key",
    signing_salt: "vBoKQ+vi",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # `:only` matches the first path segment exactly, but `mix phx.digest` renames
  # top-level files — favicon.svg becomes favicon-<hash>.svg — and that is the
  # name `~p` emits in production. Without `:only_matching` the digested favicon
  # is a 404 in prod while working perfectly in dev, where nothing is digested.
  # Directories are unaffected: "assets" and "fonts" keep their names.
  plug Plug.Static,
    at: "/",
    from: :beerocracy,
    gzip: not code_reloading?,
    only: BeerocracyWeb.static_paths(),
    only_matching: ["favicon"],
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :beerocracy
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BeerocracyWeb.Router
end
