defmodule Beerocracy.Repo.Migrations.AddVoting do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:place_votes, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :liked, :boolean, null: false
      add :place_slug, :text, null: false
      add :voter_name, :text, null: false
      add :voter_key, :text, null: false
      add :week_key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:place_votes, [:week_key, :voter_key, :place_slug],
             name: "place_votes_unique_place_vote_index"
           )

    create table(:day_votes, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :weekday, :text, null: false
      add :voter_name, :text, null: false
      add :voter_key, :text, null: false
      add :week_key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:day_votes, [:week_key, :voter_key, :weekday],
             name: "day_votes_unique_day_vote_index"
           )
  end

  def down do
    drop_if_exists unique_index(:day_votes, [:week_key, :voter_key, :weekday],
                     name: "day_votes_unique_day_vote_index"
                   )

    drop table(:day_votes)

    drop_if_exists unique_index(:place_votes, [:week_key, :voter_key, :place_slug],
                     name: "place_votes_unique_place_vote_index"
                   )

    drop table(:place_votes)
  end
end
