defmodule Beerocracy.Repo.Migrations.AddDayVoteStance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:day_votes) do
      # SQLite will not add a NOT NULL column without a default, and every vote
      # that predates the "maybe" option was a firm yes.
      add :stance, :text, null: false, default: "yes"
    end
  end

  def down do
    alter table(:day_votes) do
      remove :stance
    end
  end
end
