defmodule Beerocracy.Repo.Migrations.AddMinutes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:minute_entries, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :recorded_by, :text, null: false
      add :weekday, :text, null: false
      add :place_slug, :text, null: false
      add :week_key, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:minute_entries, [:week_key], name: "minute_entries_unique_week_index")
  end

  def down do
    drop_if_exists unique_index(:minute_entries, [:week_key],
                     name: "minute_entries_unique_week_index"
                   )

    drop table(:minute_entries)
  end
end
