defmodule Beerocracy.Repo.Migrations.AllowMultipleMinuteEntries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:minute_entries, [:week_key],
                     name: "minute_entries_unique_week_index"
                   )

    create unique_index(:minute_entries, [:week_key, :weekday, :place_slug],
             name: "minute_entries_unique_visit_index"
           )
  end

  def down do
    drop_if_exists unique_index(:minute_entries, [:week_key, :weekday, :place_slug],
                     name: "minute_entries_unique_visit_index"
                   )

    create unique_index(:minute_entries, [:week_key], name: "minute_entries_unique_week_index")
  end
end
