defmodule Beerocracy.Repo.Migrations.AddAccounts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :email, :citext
      add :display_name, :text, null: false
      add :github_login, :text, null: false
      add :github_id, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    create table(:user_identities, primary_key: false) do
      add :user_id,
          references(:users, column: :id, name: "user_identities_user_id_fkey", type: :uuid)

      add :id, :uuid, null: false, primary_key: true
      add :strategy, :text, null: false
      add :uid, :text, null: false
      add :access_token, :text
      add :access_token_expires_at, :utc_datetime_usec
      add :refresh_token, :text
    end

    create unique_index(:user_identities, [:strategy, :uid],
             name: "user_identities_unique_on_strategy_and_uid_index"
           )

    create table(:tokens, primary_key: false) do
      add :jti, :text, null: false, primary_key: true
      add :subject, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :purpose, :text, null: false
      add :extra_data, :map
      add :created_at, :utc_datetime_usec, null: false
      add :updated_at, :utc_datetime_usec, null: false
    end
  end

  def down do
    drop table(:tokens)

    drop_if_exists unique_index(:user_identities, [:strategy, :uid],
                     name: "user_identities_unique_on_strategy_and_uid_index"
                   )

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `user_identities` table without the `user_identities_user_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:user_identities)

    drop_if_exists unique_index(:users, [:github_id], name: "users_unique_github_id_index")

    drop table(:users)
  end
end
